osx_image: xcode8.3

dist: trusty

sudo: required

services:
- docker

language: node_js
node_js: '9'
os:
- linux
- osx

env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - "$HOME/.npm"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull electronuserland/electron-builder:wine; fi

install:
- npm install -g lerna
- lerna bootstrap && lerna bootstrap

script:
- cd packages/ui
- ls node_modules/.bin
- if [[ "$TRAVIS_OS_NAME" == "linux"   ]]; then docker run --rm -ti -e GH_TOKEN=$GH_TOKEN --env-file <(env | grep TRAVIS) -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:wine /bin/bash -c "npm run dist:linux"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux"   ]]; then docker run --rm -ti -e GH_TOKEN=$GH_TOKEN --env-file <(env | grep TRAVIS) -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:wine /bin/bash -c "npm run dist:win"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then npm run dist:mac; fi


before_cache:
- rm -rf $HOME/.cache/electron-builder/wine


notifications:
  email: false