version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            sudo npm install -g lerna
            lerna bootstrap && lerna bootstrap
            npm install

      - save_cache:
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/cli/node_modules
            - packages/ui/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test Core
          working_directory: ~/repo/packages/core
          command: npm test

      - run:
          name: Build and Publish Executables
          working_directory: ~/repo/packages/ui
          command: npm run dist:all

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^.*/
  tagged-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/